### ISSUE TITLE
how to output to logstash ?

### ISSUE THREAD

**Issue by 4220182** [jzwlqx/fluentd-pilot#2]

**Comment by jzwlqx** [comment]
It can but you should not need. Both logstash and fluentd are able to collect log and send to backend storage such as sls, elasticsearch, graylog2 and etc. Since fluent-pilot use fluentd internal to collect log, logstash are not needed.

However, if you are sure that you need logstash in your scenario, [this](http://stackoverflow.com/questions/23144453/fluentd-to-logstash-output-plugin) may be helpful.

**Comment by 4220182** [comment]
Because my log format is:

#Username:test1#age:23
#Username:test2#age:24
......

I found that it only supports 3 format : none json cvs ,I don't know how to format those logs .

**Comment by jzwlqx** [comment]
i will add regex format support later, that could be helpful

**Comment by 4220182** [comment]
Wonderful !
